### ISSUE TITLE
release date

### ISSUE THREAD

**Issue by GoogleCodeExporter** [damienhaynes/moving-pictures#1148]
```
What steps will reproduce the problem?
1. just use any external scraper script to catch film info
2.
3.

What is the expected output? What do you see instead?
If the scraper dont send the relase date of the film I expect that field should 
be in blank but moving-picture use current date as release date


What version of Moving Pictures are you using?  1.7.2.1582
What version of MediaPortal? 1.8
What Skin? streammedMP


Please attach a screenshot and logs if possible. When submitting log files
please submit DEBUG logs. See here for details:
http://tinyurl.com/aj65su

```

Original issue reported on code.google.com by `ruben.sp...@gmail.com` on 16 Aug 2014 at 11:04

**Comment by macxsm** [comment]
This problem also occurs using the XBMC internal filter.
The XBMC importer filter does not support the releasedate-feature. Scraping a movie with this scraper shows the release date of the movie is as the import date.

You can confirm that using the "XBMC (local)" importing a movie with the attached sample XML file. As you can see, the release date is present in this file but is not imported. Thus the scraper does not overwrite the pre-populated release date that is just "now" (the time of the import process). 

This problem was also discussed here 
http://forum.team-mediaportal.com/threads/date-of-release.132487
The workaround the problem by adding the releasedate-feature .

So please add support for this feature for the internal scrapers.

[8.Mile.(2002).(1080p).(tt0298203).(ger).(eng).nfo.zip](https://github.com/damienhaynes/moving-pictures/files/122357/8.Mile.2002.1080p.tt0298203.ger.eng.nfo.zip)
